/*
Corellium API

REST API to manage your virtual devices.

API version: 7.3.0-27831
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package corellium

import (
	"encoding/json"
	"fmt"
)

// TouchInputButtonsInner struct for TouchInputButtonsInner
type TouchInputButtonsInner struct {
	Button *Button
	string *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *TouchInputButtonsInner) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into Button
	err = json.Unmarshal(data, &dst.Button);
	if err == nil {
		jsonButton, _ := json.Marshal(dst.Button)
		if string(jsonButton) == "{}" { // empty struct
			dst.Button = nil
		} else {
			return nil // data stored in dst.Button, return on the first match
		}
	} else {
		dst.Button = nil
	}

	// try to unmarshal JSON data into string
	err = json.Unmarshal(data, &dst.string);
	if err == nil {
		jsonstring, _ := json.Marshal(dst.string)
		if string(jsonstring) == "{}" { // empty struct
			dst.string = nil
		} else {
			return nil // data stored in dst.string, return on the first match
		}
	} else {
		dst.string = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(TouchInputButtonsInner)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *TouchInputButtonsInner) MarshalJSON() ([]byte, error) {
	if src.Button != nil {
		return json.Marshal(&src.Button)
	}

	if src.string != nil {
		return json.Marshal(&src.string)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableTouchInputButtonsInner struct {
	value *TouchInputButtonsInner
	isSet bool
}

func (v NullableTouchInputButtonsInner) Get() *TouchInputButtonsInner {
	return v.value
}

func (v *NullableTouchInputButtonsInner) Set(val *TouchInputButtonsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTouchInputButtonsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTouchInputButtonsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTouchInputButtonsInner(val *TouchInputButtonsInner) *NullableTouchInputButtonsInner {
	return &NullableTouchInputButtonsInner{value: val, isSet: true}
}

func (v NullableTouchInputButtonsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTouchInputButtonsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


