/*
Corellium API

REST API to manage your virtual devices.

API version: 6.5.0-24034
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package corellium

import (
	"encoding/json"
)

// checks if the ApiError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiError{}

// ApiError 
type ApiError struct {
	// Error text
	Error string `json:"error"`
	// Error ID
	ErrorID string `json:"errorID"`
	// Upstream error description
	OriginalError NullableString `json:"originalError,omitempty"`
}

// NewApiError instantiates a new ApiError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiError(error_ string, errorID string) *ApiError {
	this := ApiError{}
	this.Error = error_
	this.ErrorID = errorID
	return &this
}

// NewApiErrorWithDefaults instantiates a new ApiError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiErrorWithDefaults() *ApiError {
	this := ApiError{}
	return &this
}

// GetError returns the Error field value
func (o *ApiError) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *ApiError) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *ApiError) SetError(v string) {
	o.Error = v
}

// GetErrorID returns the ErrorID field value
func (o *ApiError) GetErrorID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ErrorID
}

// GetErrorIDOk returns a tuple with the ErrorID field value
// and a boolean to check if the value has been set.
func (o *ApiError) GetErrorIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorID, true
}

// SetErrorID sets field value
func (o *ApiError) SetErrorID(v string) {
	o.ErrorID = v
}

// GetOriginalError returns the OriginalError field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiError) GetOriginalError() string {
	if o == nil || IsNil(o.OriginalError.Get()) {
		var ret string
		return ret
	}
	return *o.OriginalError.Get()
}

// GetOriginalErrorOk returns a tuple with the OriginalError field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiError) GetOriginalErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OriginalError.Get(), o.OriginalError.IsSet()
}

// HasOriginalError returns a boolean if a field has been set.
func (o *ApiError) HasOriginalError() bool {
	if o != nil && o.OriginalError.IsSet() {
		return true
	}

	return false
}

// SetOriginalError gets a reference to the given NullableString and assigns it to the OriginalError field.
func (o *ApiError) SetOriginalError(v string) {
	o.OriginalError.Set(&v)
}
// SetOriginalErrorNil sets the value for OriginalError to be an explicit nil
func (o *ApiError) SetOriginalErrorNil() {
	o.OriginalError.Set(nil)
}

// UnsetOriginalError ensures that no value is present for OriginalError, not even an explicit nil
func (o *ApiError) UnsetOriginalError() {
	o.OriginalError.Unset()
}

func (o ApiError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	toSerialize["errorID"] = o.ErrorID
	if o.OriginalError.IsSet() {
		toSerialize["originalError"] = o.OriginalError.Get()
	}
	return toSerialize, nil
}

type NullableApiError struct {
	value *ApiError
	isSet bool
}

func (v NullableApiError) Get() *ApiError {
	return v.value
}

func (v *NullableApiError) Set(val *ApiError) {
	v.value = val
	v.isSet = true
}

func (v NullableApiError) IsSet() bool {
	return v.isSet
}

func (v *NullableApiError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiError(val *ApiError) *NullableApiError {
	return &NullableApiError{value: val, isSet: true}
}

func (v NullableApiError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


