/*
Corellium API

REST API to manage your virtual devices.

API version: 6.5.0-23522
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package corellium

import (
	"encoding/json"
)

// checks if the CreateNetworkConnectionOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateNetworkConnectionOptions{}

// CreateNetworkConnectionOptions 
type CreateNetworkConnectionOptions struct {
	// UUIDv4
	Identifier string `json:"identifier"`
	// User specified name for this network connection. e.g. My Network Connection
	Name string `json:"name"`
	// One of the registered [network provider types](#get-/v1/network/providers)
	Provider string `json:"provider"`
	// An object containing network connection configuration data. Will vary based on network provider type. See examples.
	Config map[string]interface{} `json:"config,omitempty"`
}

// NewCreateNetworkConnectionOptions instantiates a new CreateNetworkConnectionOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateNetworkConnectionOptions(identifier string, name string, provider string) *CreateNetworkConnectionOptions {
	this := CreateNetworkConnectionOptions{}
	this.Identifier = identifier
	this.Name = name
	this.Provider = provider
	return &this
}

// NewCreateNetworkConnectionOptionsWithDefaults instantiates a new CreateNetworkConnectionOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateNetworkConnectionOptionsWithDefaults() *CreateNetworkConnectionOptions {
	this := CreateNetworkConnectionOptions{}
	return &this
}

// GetIdentifier returns the Identifier field value
func (o *CreateNetworkConnectionOptions) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *CreateNetworkConnectionOptions) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *CreateNetworkConnectionOptions) SetIdentifier(v string) {
	o.Identifier = v
}

// GetName returns the Name field value
func (o *CreateNetworkConnectionOptions) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateNetworkConnectionOptions) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateNetworkConnectionOptions) SetName(v string) {
	o.Name = v
}

// GetProvider returns the Provider field value
func (o *CreateNetworkConnectionOptions) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *CreateNetworkConnectionOptions) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *CreateNetworkConnectionOptions) SetProvider(v string) {
	o.Provider = v
}

// GetConfig returns the Config field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateNetworkConnectionOptions) GetConfig() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateNetworkConnectionOptions) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Config) {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *CreateNetworkConnectionOptions) HasConfig() bool {
	if o != nil && IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given map[string]interface{} and assigns it to the Config field.
func (o *CreateNetworkConnectionOptions) SetConfig(v map[string]interface{}) {
	o.Config = v
}

func (o CreateNetworkConnectionOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateNetworkConnectionOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identifier"] = o.Identifier
	toSerialize["name"] = o.Name
	toSerialize["provider"] = o.Provider
	if o.Config != nil {
		toSerialize["config"] = o.Config
	}
	return toSerialize, nil
}

type NullableCreateNetworkConnectionOptions struct {
	value *CreateNetworkConnectionOptions
	isSet bool
}

func (v NullableCreateNetworkConnectionOptions) Get() *CreateNetworkConnectionOptions {
	return v.value
}

func (v *NullableCreateNetworkConnectionOptions) Set(val *CreateNetworkConnectionOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateNetworkConnectionOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateNetworkConnectionOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateNetworkConnectionOptions(val *CreateNetworkConnectionOptions) *NullableCreateNetworkConnectionOptions {
	return &NullableCreateNetworkConnectionOptions{value: val, isSet: true}
}

func (v NullableCreateNetworkConnectionOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateNetworkConnectionOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


