/*
Corellium API

REST API to manage your virtual devices.

API version: 7.3.0-27831
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package corellium

import (
	"encoding/json"
)

// checks if the NetworkConnection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkConnection{}

// NetworkConnection 
type NetworkConnection struct {
	// UUIDv4
	Identifier string `json:"identifier"`
	// One of the registered [network provider types](#get-/v1/network/providers)
	Provider string `json:"provider"`
	// User specified name for this network connection. e.g., \"My Network Connection\"
	Name string `json:"name"`
	// An object containing network connection configuration data. Will vary based on network provider type.
	Config map[string]interface{} `json:"config"`
	// An object where the keys are project IDs and the values are {@link ProjectNetworkState} objects representing the state of each project.
	Projects []ProjectNetworkState `json:"projects,omitempty"`
	// Created Date in ISO-8601 format e.g., \"2022-05-06T02:39:23.000Z\"
	CreatedAt string `json:"createdAt"`
	// Updated Date in ISO-8601 format e.g., \"2022-05-06T02:39:23.000Z\"
	UpdatedAt string `json:"updatedAt"`
	// UUIDv4 of the user who created this record.
	CreatedBy string `json:"createdBy"`
	// UUIDv4 of the user who last updated this record.
	UpdatedBy string `json:"updatedBy"`
}

// NewNetworkConnection instantiates a new NetworkConnection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkConnection(identifier string, provider string, name string, config map[string]interface{}, createdAt string, updatedAt string, createdBy string, updatedBy string) *NetworkConnection {
	this := NetworkConnection{}
	this.Identifier = identifier
	this.Provider = provider
	this.Name = name
	this.Config = config
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.CreatedBy = createdBy
	this.UpdatedBy = updatedBy
	return &this
}

// NewNetworkConnectionWithDefaults instantiates a new NetworkConnection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkConnectionWithDefaults() *NetworkConnection {
	this := NetworkConnection{}
	return &this
}

// GetIdentifier returns the Identifier field value
func (o *NetworkConnection) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *NetworkConnection) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *NetworkConnection) SetIdentifier(v string) {
	o.Identifier = v
}

// GetProvider returns the Provider field value
func (o *NetworkConnection) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *NetworkConnection) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *NetworkConnection) SetProvider(v string) {
	o.Provider = v
}

// GetName returns the Name field value
func (o *NetworkConnection) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NetworkConnection) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NetworkConnection) SetName(v string) {
	o.Name = v
}

// GetConfig returns the Config field value
func (o *NetworkConnection) GetConfig() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *NetworkConnection) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// SetConfig sets field value
func (o *NetworkConnection) SetConfig(v map[string]interface{}) {
	o.Config = v
}

// GetProjects returns the Projects field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NetworkConnection) GetProjects() []ProjectNetworkState {
	if o == nil {
		var ret []ProjectNetworkState
		return ret
	}
	return o.Projects
}

// GetProjectsOk returns a tuple with the Projects field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NetworkConnection) GetProjectsOk() ([]ProjectNetworkState, bool) {
	if o == nil || IsNil(o.Projects) {
		return nil, false
	}
	return o.Projects, true
}

// HasProjects returns a boolean if a field has been set.
func (o *NetworkConnection) HasProjects() bool {
	if o != nil && IsNil(o.Projects) {
		return true
	}

	return false
}

// SetProjects gets a reference to the given []ProjectNetworkState and assigns it to the Projects field.
func (o *NetworkConnection) SetProjects(v []ProjectNetworkState) {
	o.Projects = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *NetworkConnection) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *NetworkConnection) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *NetworkConnection) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *NetworkConnection) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *NetworkConnection) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *NetworkConnection) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *NetworkConnection) GetCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *NetworkConnection) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *NetworkConnection) SetCreatedBy(v string) {
	o.CreatedBy = v
}

// GetUpdatedBy returns the UpdatedBy field value
func (o *NetworkConnection) GetUpdatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedBy
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value
// and a boolean to check if the value has been set.
func (o *NetworkConnection) GetUpdatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedBy, true
}

// SetUpdatedBy sets field value
func (o *NetworkConnection) SetUpdatedBy(v string) {
	o.UpdatedBy = v
}

func (o NetworkConnection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkConnection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identifier"] = o.Identifier
	toSerialize["provider"] = o.Provider
	toSerialize["name"] = o.Name
	toSerialize["config"] = o.Config
	if o.Projects != nil {
		toSerialize["projects"] = o.Projects
	}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["createdBy"] = o.CreatedBy
	toSerialize["updatedBy"] = o.UpdatedBy
	return toSerialize, nil
}

type NullableNetworkConnection struct {
	value *NetworkConnection
	isSet bool
}

func (v NullableNetworkConnection) Get() *NetworkConnection {
	return v.value
}

func (v *NullableNetworkConnection) Set(val *NetworkConnection) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkConnection) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkConnection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkConnection(val *NetworkConnection) *NullableNetworkConnection {
	return &NullableNetworkConnection{value: val, isSet: true}
}

func (v NullableNetworkConnection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkConnection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


