name: Update Bindings
on:
  schedule:
    - cron: '0 15 * * 1-4' # Run every Monday through Thursday at 10:00 am Cayman time (15:00 UTC)
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - 'staging'
      - 'main'
  
permissions:
  contents: write
  pull-requests: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Go
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version: 1.20

    - name: Install OpenAPI Generator
      run: yarn global add @openapitools/openapi-generator-cli

    - name: Generate API bindings
      run: |
        rm -r test/
        openapi-generator-cli generate

    - name: Commit and push changes
      run: |
        git config --local user.email "modabot@ai.moda"
        git config --local user.name "modabot"

        # Check if there are any changes
        git add -A
        if git status | grep -q "Changes to be committed"; then
          # Create a new branch with a timestamp
          branch_name="update-bindings-$(TZ='UTC' date --iso-8601=seconds | sed s/:/-/g)"
          git checkout -b "$branch_name"

          git commit -m "Update Go API bindings"
          git push --set-upstream origin "$branch_name"

          pr_title="Update Go API bindings"
          pr_body="This PR updates the Go API bindings with the latest changes."
          base_branch="main"
          gh pr create --title "$pr_title" --body "$pr_body" --base "$base_branch" --head "$branch_name"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
